// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTTlikanwNF3x8NmcVcjXdxBffBmknbdY',
    appId: '1:642813170673:web:0e52cba018eb243dd32a50',
    messagingSenderId: '642813170673',
    projectId: 'newsapp-8e454',
    authDomain: 'newsapp-8e454.firebaseapp.com',
    storageBucket: 'newsapp-8e454.appspot.com',
    measurementId: 'G-718DSZEWBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyZ-H3BAox8i1Z96cGrYuAf5CV6cgxqw',
    appId: '1:642813170673:android:c00d7987b73ab928d32a50',
    messagingSenderId: '642813170673',
    projectId: 'newsapp-8e454',
    storageBucket: 'newsapp-8e454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPGElfYLwuJRXj3v6YcG3nlloIvddWZY',
    appId: '1:642813170673:ios:e4505edf043e02ded32a50',
    messagingSenderId: '642813170673',
    projectId: 'newsapp-8e454',
    storageBucket: 'newsapp-8e454.appspot.com',
    iosClientId:
        '642813170673-lb1b37pemi35m2srgl845a2qbbf56rmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPGElfYLwuJRXj3v6YcG3nlloIvddWZY',
    appId: '1:642813170673:ios:e4505edf043e02ded32a50',
    messagingSenderId: '642813170673',
    projectId: 'newsapp-8e454',
    storageBucket: 'newsapp-8e454.appspot.com',
    iosClientId:
        '642813170673-lb1b37pemi35m2srgl845a2qbbf56rmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
